# -*- coding: utf-8 -*-
"""Recomendação de Cursos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PEWnJ6kNQm6FN3MEaydJSBLdVxXoAcTB
"""

!pip install -q google-generativeai

import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

catalogo_cursos = [
    {
        "titulo": "Curso de TBO",
        "descricao": "Capacitação sobre Técnicas Básicas Operacionais voltadas para a atuação em ambientes industriais.",
        "tags": ["tbo", "operações industriais", "produção", "zona franca de manaus"],
        "area": "Produção Industrial"
    },
    {
        "titulo": "NR 12 - Máquinas e Equipamentos",
        "descricao": "Curso sobre segurança no trabalho com máquinas e equipamentos conforme a Norma Regulamentadora 12.",
        "tags": ["nr12", "segurança do trabalho", "máquinas", "equipamentos", "zona franca de manaus"],
        "area": "Segurança do Trabalho"
    },
    {
        "titulo": "Leitura de Componentes",
        "descricao": "Curso introdutório sobre identificação e leitura de componentes eletrônicos em circuitos.",
        "tags": ["componentes eletrônicos", "eletrônica básica", "leitura de componentes", "zona franca de manaus"],
        "area": "Eletrônica"
    },
    {
        "titulo": "Técnicas de Soldagem Eletrônica",
        "descricao": "Curso teórico sobre princípios e técnicas de soldagem de componentes eletrônicos.",
        "tags": ["soldagem eletrônica", "eletrônica", "técnicas de soldagem", "zona franca de manaus"],
        "area": "Eletrônica"
    },
    {
        "titulo": "Curso de 5S",
        "descricao": "Capacitação nos cinco sensos japoneses voltados para a organização e produtividade no ambiente de trabalho.",
        "tags": ["5s", "organização", "produtividade", "manufatura", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Curso de 8S",
        "descricao": "Curso avançado que amplia os conceitos do 5S com foco em sustentabilidade e disciplina.",
        "tags": ["8s", "organização", "gestão", "sustentabilidade", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Curso de 10S",
        "descricao": "Treinamento que incorpora práticas de excelência e segurança aos conceitos do 5S e 8S.",
        "tags": ["10s", "excelência operacional", "segurança", "organização", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Metrologia Industrial",
        "descricao": "Curso sobre técnicas de medição e controle dimensional aplicadas na indústria.",
        "tags": ["metrologia", "medição", "controle de qualidade", "indústria", "zona franca de manaus"],
        "area": "Qualidade Industrial"
    },
    {
        "titulo": "ESD - Descarga Eletrostática",
        "descricao": "Capacitação sobre prevenção de danos causados por descarga eletrostática em ambientes eletrônicos.",
        "tags": ["esd", "descarga eletrostática", "eletrônica", "prevenção", "zona franca de manaus"],
        "area": "Eletrônica"
    },
    {
        "titulo": "Almoxarifado",
        "descricao": "Curso voltado para organização, controle e gestão de materiais em almoxarifados industriais.",
        "tags": ["almoxarifado", "logística", "gestão de materiais", "armazenamento", "zona franca de manaus"],
        "area": "Logística"
    },
    {
        "titulo": "Inspetor da Qualidade",
        "descricao": "Curso abrangente sobre os princípios e práticas da inspeção de qualidade na indústria.",
        "tags": ["qualidade", "inspeção", "controle de qualidade", "zona franca de manaus"],
        "area": "Qualidade Industrial"
    },
    {
        "titulo": "Operador de Produção",
        "descricao": "Capacitação para atuação em linhas de produção, com foco em processos industriais e boas práticas operacionais.",
        "tags": ["produção", "processos industriais", "linha de produção", "zona franca de manaus"],
        "area": "Produção Industrial"
    },
    {
        "titulo": "Operador de SMD",
        "descricao": "Curso voltado à operação de máquinas de montagem de componentes em tecnologia SMD.",
        "tags": ["smd", "montagem eletrônica", "componentes de superfície", "zona franca de manaus"],
        "area": "Eletrônica"
    },
    {
        "titulo": "Ferramentas da Qualidade",
        "descricao": "Curso que apresenta as principais ferramentas utilizadas no controle e melhoria da qualidade nos processos.",
        "tags": ["qualidade", "ferramentas da qualidade", "controle de processos", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "ISO 9001",
        "descricao": "Capacitação sobre os requisitos da norma ISO 9001 e sua aplicação nos sistemas de gestão da qualidade.",
        "tags": ["iso 9001", "qualidade", "sistema de gestão", "auditoria", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Auxiliar de Produção",
        "descricao": "Formação básica para apoio nas atividades da linha de produção industrial.",
        "tags": ["auxiliar de produção", "produção industrial", "apoio operacional", "zona franca de manaus"],
        "area": "Produção Industrial"
    },
    {
        "titulo": "Gestão da Qualidade",
        "descricao": "Curso completo sobre os fundamentos e práticas de gestão da qualidade em ambientes industriais.",
        "tags": ["gestão da qualidade", "melhoria contínua", "processos", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Operador de Máquina Injetora",
        "descricao": "Capacitação para operação e controle de máquinas injetoras em processos de transformação de plásticos.",
        "tags": ["máquina injetora", "injeção plástica", "processo industrial", "zona franca de manaus"],
        "area": "Produção Industrial"
    },
    {
        "titulo": "Leitura e Interpretação de Desenho Técnico",
        "descricao": "Curso para desenvolver a habilidade de ler, entender e interpretar desenhos técnicos industriais.",
        "tags": ["desenho técnico", "interpretação", "projetos mecânicos", "zona franca de manaus"],
        "area": "Engenharia e Projetos"
    },
    {
        "titulo": "Matemática Aplicada",
        "descricao": "Curso de reforço em conceitos matemáticos aplicados ao ambiente industrial e técnico.",
        "tags": ["matemática", "cálculo técnico", "matemática industrial", "zona franca de manaus"],
        "area": "Formação Básica"
    },
    {
        "titulo": "Analista de Produção",
        "descricao": "Capacitação para análise, planejamento e melhoria de processos produtivos industriais.",
        "tags": ["produção", "análise de processos", "planejamento", "zona franca de manaus"],
        "area": "Produção Industrial"
    },
    {
        "titulo": "Gestão da Produção",
        "descricao": "Curso sobre princípios e práticas de planejamento, controle e otimização da produção industrial.",
        "tags": ["gestão da produção", "controle de produção", "otimização", "zona franca de manaus"],
        "area": "Produção Industrial"
    },
    {
        "titulo": "Lean Manufacturing",
        "descricao": "Capacitação sobre os conceitos e ferramentas do sistema Lean voltado à eliminação de desperdícios e melhoria contínua.",
        "tags": ["lean", "lean manufacturing", "produção enxuta", "melhoria contínua", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Seis Sigma",
        "descricao": "Curso introdutório sobre a metodologia Seis Sigma voltada à redução de variações e defeitos em processos.",
        "tags": ["seis sigma", "6 sigma", "qualidade", "melhoria de processos", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "FMEA",
        "descricao": "Curso prático sobre Análise de Modos de Falha e Efeitos, utilizado para prevenção de falhas em produtos e processos.",
        "tags": ["fmea", "análise de falhas", "qualidade", "processos", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "MASP",
        "descricao": "Capacitação em Metodologia de Análise e Solução de Problemas aplicada à melhoria de processos.",
        "tags": ["masp", "análise de problemas", "qualidade", "melhoria contínua", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "PDCA",
        "descricao": "Curso sobre o ciclo PDCA e sua aplicação no controle e melhoria de processos organizacionais.",
        "tags": ["pdca", "planejamento", "controle", "melhoria contínua", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Metodologia 8D",
        "descricao": "Capacitação na metodologia 8D para solução estruturada de problemas na indústria.",
        "tags": ["8d", "solução de problemas", "qualidade", "melhoria de processos", "zona franca de manaus"],
        "area": "Gestão da Qualidade"
    },
    {
        "titulo": "Engenharia de Tempos e Métodos",
        "descricao": "Curso técnico sobre análise de métodos e medição de tempos para otimização da produção.",
        "tags": ["tempos e métodos", "engenharia de produção", "otimização", "zona franca de manaus"],
        "area": "Engenharia de Produção"
    },
    {
        "titulo": "SAP",
        "descricao": "Curso introdutório sobre o sistema SAP com foco em operações industriais e gestão empresarial.",
        "tags": ["sap", "sistemas integrados", "erp", "gestão empresarial", "zona franca de manaus"],
        "area": "Sistemas de Gestão"
    }
]



import google.generativeai as genai

model = genai.GenerativeModel('gemini-2.0-flash')

interesse_usuario = input("Olá! Para te ajudar a encontrar o curso ideal, me diga o que te interessa aprender ou quais são seus objetivos: ")
print(f"Legal! Você mencionou: {interesse_usuario}. Vamos buscar algumas sugestões para você!")

prompt = f"""
Você é um especialista em carreiras e desenvolvimento profissional com um tom amigável e motivador.
Com base nos seguintes interesses do usuário: "{interesse_usuario}",
recomende até 3 cursos relevantes do seguinte catálogo:

{catalogo_cursos}

Para cada recomendação, explique de forma inspiradora como o curso pode ajudar o usuário a alcançar seus objetivos de carreira na área industrial de Manaus.
Limite a resposta a no máximo 120 palavras.
"""

response = model.generate_content(prompt)
print("\nRecomendações de cursos:")
print(response.text)